#server configurations
server:
  port: 8081
  servlet:
    session:
      persistent: false

#Debug configurations
logging:
  level:
    org:
      springframework:
        security: DEBUG
#Google calendar configurations
google:
  listEventUrl: https://www.googleapis.com/calendar/v3/calendars/primary/events
app:
  name: Event Planner
  timeZone : +05:30
  calendar:
    id: primary

#Spring Configurations
spring:
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 162662766017-0bik6pg2kqsv2nkc818s4ec30124ppnc.apps.googleusercontent.com
            client-secret: eYeIEPRDShJISVvEvm0pJYOj
            authorizationGrantType: authorization_code
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/drive
              -
  servlet:
    multipart:
      enabled: 'true'
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
